title: Raul Dipeas
author:
  name: © Raul Dipeas
  email: contato@rauldipeas.com.br
description: >-
  Este é o meu blog pessoal, onde eu escrevo sobre tecnologia, produção musical, cultura cinematográfica e o meu cotidiano.
baseurl: "/"
url: "rauldipeas.com.br"
favicon: "/assets/images/avatar/avatar 1.svg"
#remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons
sass:
  quiet_deps: true
  silence_deprecations: [import]
theme: minima
minima:
  date_format: "%d/%m/%y"
#  hide_site_feed_link: false
  show_excerpts: true
  skin: auto
  social_links:
    - title: Estúdio Debian
      icon: carla
      url: "https://estudio-debian.github.io"
    - title: Me siga por RSS
      icon: akregator
      url: "/feed.xml"
    - title: Me siga no Instagram
      icon: instagram
      url: "https://instagram.com/raul_dipeas"
    - title: Me siga no TikTok
      icon: tiktok
      url: "https://tiktok.com/@rauldipeas"
    - title: Me siga no YouTube
      icon: youtube
      url: "https://youtube.com/rauldipeas"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
