#!/bin/bash
set -e
rm -f "$HOME"/.local/share/applications/uds.desktop
cd /tmp
rm -f /tmp/uds.deb
wget -q --show-progress https://archive.org/download/ubuntuderivativesstudio/uds.deb
sudo apt install --reinstall ./uds.deb