name: Cópia de segurança da conta do Mastodon
on:
    push:
      branches:
        - main
    schedule:
      - cron: '0 10,22 * * *'
    workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Backup Mastodon Account
        uses: potatoqualitee/fossilize@v2
        id: backup
        with:
          server: mastodon.social
        env:
          ACCESS_TOKEN: ${{ secrets.MASTODON_TOKEN }}